apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-accounts
  namespace: group1-team8
  labels:
    app: team8-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-accounts
  template:
    metadata:
      labels:
        app: team8-accounts
    spec:
      containers:
      - name: team8-accounts
        image: k8s-vga-worker1:5000/team8-accounts:latest
        ports:
        - containerPort: 9020
