apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-zipkin
  namespace: group1-team8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-zipkin
  template:
    metadata:
      labels:
        app: team8-zipkin
    spec:
      containers:
        - name: team8-zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
          env:
            - name: STORAGE_TYPE
              value: mem
---
apiVersion: v1
kind: Service
metadata:
  name: team8-zipkin
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30880