server: 
  port: 8761

spring:
  application:
    name: team8-eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false