apiVersion: apps/v1 # 필수 표준 apps/v1
kind: Deployment
metadata:
  name: team8-cards
  namespace: group1-team8
  labels:
    app: team8-cards
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team8-cards
  template:
    metadata:
      labels:
        app: team8-cards
    spec:
      containers:
      - name: team8-cards
        image: k8s-vga-worker1:5000/team8-cards:latest
        ports:
        - containerPort: 9000
