apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-loans
  namespace: group1-team8
  labels:
    app: team8-loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-loans
  template:
    metadata:
      labels:
        app: team8-loans
    spec:
      containers:
      - name: team8-loans
        image: k8s-vga-worker1:5000/team8-loans:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: team8-loans
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-loans
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30812
