apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-jaeger-collector
  namespace: group1-team8
  labels:
    app: team8-jaeger-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-jaeger-collector
  template:
    metadata:
      labels:
        app: team8-jaeger-collector
    spec:
      containers:
      - name: team8-jaeger-collector
        image: jaegertracing/all-in-one:1.47.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16686 # UI
        - containerPort: 14250 # gRPC 기반 Collector 수신 포트 (애플리케이션에서 Collector로 직접 데이터 전송)
        - containerPort: 14268 # HTTP 기반 Collector 수신 포트 (애플리케이션에서 Collector로 직접 데이터 전송)
        - containerPort: 14269 # admin-port
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://team8-elasticsearch:9200"
        - name: JAEGER_SAMPLER_TYPE
          value: "const"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"            
---
apiVersion: v1
kind: Service
metadata:
  name: team8-jaeger-collector
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-jaeger-collector
  ports:
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
      nodePort: 30870
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      nodePort: 30871
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: 14250
      nodePort: 30872
    - name: admin-port
      port: 14269
      targetPort: 14269
      nodePort: 30873