apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      
    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-accounts:80' ]
      - job_name: 'loans'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-loans:80' ]
      - job_name: 'cards'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-cards:80' ]
      - job_name: 'gatewayserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-gatewayserver:8080' ]
      - job_name: 'eurekaserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-eureka:80' ]
      - job_name: 'configserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-configserver:8888' ]
      - job_name: 'jaeger-collector'
        static_configs:
          - targets: [ 'team8-jaeger-collector:14269' ]
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
      - job_name: 'kubernetes-kubelet'
        scheme: https
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __metrics_path__
          replacement: /metrics/cadvisor
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):(?:\d+);(\d+)
          replacement: $1:$2
          target_label: __address__