apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      
    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-accounts:9020' ]
      - job_name: 'loans'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-loans:9010' ]
      - job_name: 'cards'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-cards:9000' ]
      - job_name: 'gatewayserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-gatewayserver:8080' ]
      - job_name: 'eurekaserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-eureka:8761' ]
      - job_name: 'configserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-configserver:8888' ]