apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # 필요에 따라 조정
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - group1-team8
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: "team8-(accounts|loans|cards|gatewayserver|eureka|configserver|jaeger-collector)"
            action: keep
          - source_labels: [__meta_kubernetes_service_port_name]
            regex: "http|metrics"
            action: keep
          - source_labels: [__meta_kubernetes_service_name]
            target_label: job

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - group1-team8
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: "team8-(accounts|loans|cards|gatewayserver|eureka|configserver|jaeger-collector)"
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: "http|metrics"
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: job

#Kubernetes에서는 기본적으로 서비스 어카운트(ServiceAccount)에 리소스 접근 권한이 부여되지 않습니다. 
#group1-team8 네임스페이스의 default 서비스 어카운트는 아무런 추가 권한 없이 사용되고 있으며, 
#Prometheus가 동작하려면 최소한 pods와 services 리소스에 대한 list와 watch 권한이 필요합니다.
