apiVersion: v1
kind: Service
metadata:
  name: team8-prometheus
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30883