apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      
    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-accounts:80' ]
      - job_name: 'loans'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-loans:80' ]
      - job_name: 'cards'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-cards:80' ]
      - job_name: 'gatewayserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-gatewayserver:80' ]
      - job_name: 'eurekaserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-eureka:80' ]
      - job_name: 'configserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-configserver:8888' ]
      # - job_name: 'jaeger-collector'
      #   metrics_path: /metrics
      #   static_configs:
      #     - targets: [ 'team8-jaeger-collector:14269' ]

      # - job_name: 'kubernetes-nodes'
      #   static_configs:
      #   - targets:
      #     - 192.168.100.222:10250
      #     - 192.168.100.223:10250
      #   scheme: https
      #   tls_config:
      #     insecure_skip_verify: true