apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      
    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-accounts:80' ]
      - job_name: 'loans'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-loans:80' ]
      - job_name: 'cards'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-cards:80' ]
      - job_name: 'gatewayserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-gatewayserver:8080' ]
      - job_name: 'eurekaserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-eureka:80' ]
      - job_name: 'configserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'team8-configserver:8888' ]

    # 노드 메트릭
    - job_name: 'kubernetes-nodes'
      scheme: https
      kubernetes_sd_configs:
      - role: node
      tls_config:
        insecure_skip_verify: true  # 인증서 검증 생략 (테스트용)
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: ${1}:10250  # Kubelet 포트 명시

    # Jaeger Collector (metrics_path 명시)
      - job_name: 'jaeger-collector'
        metrics_path: /metrics
        static_configs:
        - targets: [ 'team8-jaeger-collector:14269' ]