apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      
    scrape_configs:
      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        eureka_sd_configs:
          - server: 'http://team8-eureka:80/eureka'

      - job_name: 'accounts'
        metrics_path: '/actuator/prometheus'
        eureka_sd_configs:
          - server: 'http://team8-eureka:80/eureka'    