apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-prometheus-config
  namespace: group1-team8
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - group1-team8  # team8이 속한 네임스페이스 지정

        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: "team8-(accounts|loans|cards|gatewayserver|eureka|configserver|jaeger-collector)"
            action: keep
          - source_labels: [__meta_kubernetes_service_port_name]
            regex: "http|metrics"
            action: keep
          - source_labels: [__meta_kubernetes_service_name]
            target_label: job
          
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - group1-team8

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: "team8-(accounts|loans|cards|gatewayserver|eureka|configserver|jaeger-collector)"
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: "http|metrics"
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: job