apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: group1-team8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: eazybytes/configserver:s12
        ports:
        - containerPort: 8071
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8071
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: group1-team8
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
