apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: group1-team4  

resources:
  - configmap.yml
  - configserver.yml
  - eurekaserver.yml
  - gatewayserver.yml
  - accounts.yml
  - loans.yml
  - cards.yml

commonLabels:
  app: team4

commonAnnotations:
  createdBy: "kustomize"

