apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/DATA1/team8/grafana"