apiVersion: v1
kind: ConfigMap
metadata:
  name: team8-grafana-config
  namespace: group1-team8
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://team8-prometheus:9090
        isDefault: true
        editable: true
        jsonData:
          httpMethod: GET