apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: group1-team8
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management  # 관리 UI가 포함된 RabbitMQ 이미지 사용
          ports:
            - containerPort: 5672  # AMQP 프로토콜 포트
            - containerPort: 15672 # RabbitMQ 관리 UI 포트
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"