server:
  port: 8888  # Config Server 기본 포트

spring:
  application:
    name: team8-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seo-dk/work  # ✅ 설정을 가져올 GitHub 저장소
          clone-on-start: true  # 서버 시작 시 Git에서 설정을 자동으로 가져옴
          default-label: main  # 기본적으로 main 브랜치 사용
          search-paths: config  # ✅ Git 저장소 내 설정 파일이 있는 경로 (예: work/config/)
