apiVersion: v1
kind: Service
metadata:
  name: team8-gatewayserver
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-gatewayserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30860
