apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-sample
  namespace: group1-team8
  labels:
    app: team8-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-sample
  template:
    metadata:
      labels:
        app: team8-sample
    spec:
      containers:
        - name: team8-sample
          image: k8s-vga-worker1:5000/team8-sample:latest
          ports:
            - containerPort: 8080
          env:
          - name: OTEL_SERVICE_NAME
            value: "team8-sample"
          - name: OTEL_TRACES_EXPORTER
            value: "jaeger"
          - name: OTEL_TRACES_SAMPLER
            value: "always_on"
          - name: OTEL_LOG_LEVEL
            value: "DEBUG"            
---
apiVersion: v1
kind: Service
metadata:
  name: team8-sample
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30806