# 모든 마이크로서비스에 공통으로 적용되는 설정 파일
spring:
  cloud:
    config:
      fail-fast: true  # Config Server 연결 실패 시 애플리케이션 실행을 중단
      retry:
        max-attempts: 5  # Config Server 연결 실패 시 최대 5번까지 재시도

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
      
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true      
  metrics:
    export:
      prometheus:
        enabled: true

