server:
  port: 8080  # Gateway 서버 포트 (기본값: 8080)

spring:
  application:
    name: gatewayserver  # Config Server에서 가져올 이름

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Eureka에서 서비스 목록 자동 감지
          lower-case-service-id: true  # 서비스 ID를 소문자로 변환하여 매칭
      routes:

        - id: accounts-service  # eureka team8-accounts 서비스 라우팅
          uri: lb://team8-accounts
          predicates:
            - Path=/accounts/** # /accounts 로 시작하는 모든 요청을 매핑

        - id: cards-service  # eureka team8-cards 서비스 라우팅
          uri: lb://team8-cards
          predicates:
            - Path=/cards/** # /cards 로 시작하는 모든 요청을 매핑

        - id: loans-service  # eureka team8-loans 서비스 라우팅
          uri: lb://team8-loans
          predicates:
            - Path=/loans/** # /loans 로 시작하는 모든 요청을 매핑

eureka:
  client:
    service-url:
      ## defaultZone: http://team8-eureka:80/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true    

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,gateway"  # 'gateway' 명시적으로 추가
  endpoint:
    gateway:
      enabled: true  # Gateway Actuator 엔드포인트 활성화


info:
  app:
    name: Gateway Server
    description: Spring Cloud Gateway for Team8
    version: 1.0.0
