apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-configserver
  namespace: group1-team8
  labels:
    app: team8-configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-configserver
  template:
    metadata:
      labels:
        app: team8-configserver
    spec:
      containers:
      - name: team8-configserver
        image: k8s-vga-worker1:5000/team8-configserver:latest
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: team8-configserver
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30830
