apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-demo
  namespace: group1-team8
  labels:
    app: team8-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-demo
  template:
    metadata:
      labels:
        app: team8-demo
    spec:
      containers:
        - name: team8-demo
          image: k8s-vga-worker1:5000/team8-demo:latest
          ports:
            - containerPort: 8080
          env:
          - name: JAEGER_ENDPOINT
            value: "http://192.168.100.221:14250"
          - name: JAEGER_AGENT_HOST
            value: "localhost"
          - name: JAEGER_AGENT_PORT
            value: "6831"

        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.47.0
          ports:
          - containerPort: 6831
          args:
          - "--reporter.grpc.host-port=192.168.100.221:14250"    
---
apiVersion: v1
kind: Service
metadata:
  name: team8-demo
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30800