apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-demo
  namespace: group1-team8
  labels:
    app: team8-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-demo
  template:
    metadata:
      labels:
        app: team8-demo
    spec:
      containers:
        - name: team8-demo
          image: k8s-vga-worker1:5000/team8-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: "team8-demo"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "team8-jaeger-collector:14250"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_METRICS_EXPORTER
              value: "none"  # OTLP 메트릭 비활성화
            - name: OTEL_LOGS_EXPORTER
              value: "none"  # 로그 비활성화  
---
apiVersion: v1
kind: Service
metadata:
  name: team8-demo
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30800