apiVersion: apps/v1 # 필수 표준 apps/v1
kind: Deployment
metadata:
  name: team8-demo
  namespace: group1-team8
  labels:
    app: team8-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-demo
  template:
    metadata:
      labels:
        app: team8-demo
    spec:
      containers:
      - name: team8-demo
        image: k8s-vga-worker1:5000/team8-demo:latest
        ports:
        - containerPort: 8080
