apiVersion: v1
kind: Service
metadata:
  name: team8-accounts
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9020
      nodePort: 30840
