apiVersion: v1
kind: Service
metadata:
  name: team8-configserver
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30850
