apiVersion: v1
kind: Service
metadata:
  name: team8-eureka
  namespace: group1-team8
spec:
  type: NodePort # 외부에서 접근할 수 있는 IP 주소가 할당
  selector:
    app: team8-eureka # Deployment와 연결되는 selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 30890
