apiVersion: v1
kind: Service
metadata:
  name: team8-loans
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: team8-loans
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9010
      nodePort: 30830
