apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-loans
  namespace: group1-team8
  labels:
    app: team8-loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team8-loans
  template:
    metadata:
      labels:
        app: team8-loans
    spec:
      containers:
      - name: team8-loans
        image: k8s-vga-worker1:5000/team8-loans:latest
        ports:
        - containerPort: 9010
