apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: group1-team8
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp-port
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30880

    - name: amqp-ui-port
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30881