apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-jenkins
  namespace: group1-team8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: k8s-vga-worker1:5000/group1-team8-jenkins
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock #Docker 실행 가능하도록 소켓 마운트
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
